baseURL = "https://adolforismos.com/"
contentdir = "content"
copyright = "© Adolfo Ramírez Corona"
enableEmoji = true
googleAnalytics = "UA-6029436-1"
languageCode = "es-mx"
layoutdir = "layouts"
paginate = 10
pluralizelisttitles = false
publishdir = "public"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "vs"
theme = "ezhil"
title = "Adolfo Ramírez Corona"
[blackfriday]
hrefTargetBlank = true
[[menu.main]]
name = "libros"
url = "/libros/"
weight = 6
[[menu.main]]
name = "podcast"
url = "https://anchor.fm/meditacionpsicoterapeutica"
weight = 3
[[menu.main]]
name = "micromeditaciones"
url = "https://micromeditaciones.substack.com"
weight = 2
[[menu.main]]
name = "english"
url = "https://medium.com/@adolforismos"
weight = 8
[[menu.main]]
name = "proyectos"
url = "/proyectos/"
weight = 5
[[menu.main]]
name = "blog"
url = "/blog/"
weight = 4
[[menu.main]]
name = "inicio"
url = "/"
weight = 1
[params]
address = "Ciudad de México, México"
author = "adolforismos"
background = "img/adolforamirezcorona.png"
dateform = "2006.01.02"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Escritor, psicoterapeuta, coach, educador, especialista en audiencias y medios."
disableDisqusTypes = ["page,blog,minipost,service,cursos"]
favicon = "img/adolforamirezcorona.png"
faviconfile = "img/adolforamirezcorona.png"
featherIconsCDN = true
highlightjs = true
mainSections = ["blog"]
mode = "auto"
name = "Adolfo Ramírez Corona"
subtitle = "Escritor, psicoterapeuta, coach, educador, especialista en audiencias y medios."
year = "2019"
[[params.social]]
icon = "twitter"
name = "twitter"
url = "https://twitter.com/adolforismos"
[[params.social]]
icon = "instagram"
title = "instagram"
url = "https://www.instagram.com/adolforamirez"
[[params.social]]
icon = "mail"
title = "email"
url = "mailto:adolforamirez@gmail.com"
[[params.social]]
icon = "rss"
title = "rss"
url = "https://adolforismos.com/index.xml"
[taxonomies]
category = "categories"
tag = "tags"
