baseURL = "https://adolforismos.com/"
# disablePathToLower = "true"
languageCode = "es-mx"
title = "adolfo ramírez corona"
theme = "cocoa-eh"
preserveTaxonomyNames = true
enableEmoji = true
contentdir = "content"
canonifyurls = true
layoutdir = "layouts"
publishdir = "public"
author = "ARC"
pluralizelisttitles = false

[blackfriday]
hrefTargetBlank = true




[permalinks]
#blog = "blog/:slug/"
blog = "blog/:slug/"

[taxonomies]
category = "categories"
tag = "tags"

[params]
dateform = "2006.01.02"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "adolfo ramírez corona"
#logofile = "img/IMG_6988.png"
logofile = "img/adolforamirezcorona.png"
#logofile = "img/arc.png"
faviconfile = "img/adolforamirezcorona.png"
highlightjs = true
lang = "es"
github = "adolforismos"
email = "contacto@adolforamirez.com"
# linkedin = "john-example-aa80ue8è"
twitter = "adolforismos"
instagram = "adolforamirez"
youtube = "adolforamirezcorona"
soundcloud = "adolforamirezcorona"
googleAnalytics = "UA-6029436-1"





#canonifyurls = true
# contentdir = "content"
# languageCode = "en-US"
# layoutdir = "layouts"
#publishdir = "public"
#author = "Adolfo Ramírez Corona"
# title = "Cocoa Enhanced"
# disqusshortname = ""
#pluralizelisttitles = false

# [permalinks]
# blog = "blog/:slug/"

# [params]
# dateform = "Jan 2, 2006"
# dateformfull = "Mon Jan 2 2006 15:04:05 MST"
# description = "Example blog"
# logofile = "img/logo.png"
# faviconfile = "img/logo.png"
# highlightjs = true
# lang = "en"
# github = "example"
# email = "you@example.com"
# linkedin = "john-example-aa80ue8è"
# twitter = "@example"
