baseURL = "https://adolforismos.com/"
languageCode = "es-mx"
title = "Adolfo Ramírez Corona"
theme = "ezhil"
enableEmoji = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
pluralizelisttitles = false
paginate = 10
googleAnalytics = "UA-6029436-1"
copyright = "© Adolfo Ramírez Corona"
# DefaultContentLanguage  =  "es"  

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[blackfriday]
hrefTargetBlank = true

[taxonomies]
category = "categories"
tag = "tags"

[params]
    description = "Psicoterapeuta, escritor, budista, educador, especialista en audiencias y medios."
    subtitle = "Psicoterapeuta, escritor, budista, educador, especialista en audiencias y medios.."
    mainSections = ["blog"]
    dateform = "2006.01.02"
    dateformfull = "Mon Jan 2 2006 15:04:05 MST"
    faviconfile = "img/adolforamirezcorona.png"
    highlightjs = true
    name = "Adolfo Ramírez Corona"
    author = "adolforismos"
    address = "Ciudad de México, México"
    year = "2019"
    background = "img/adolforamirezcorona.png"
    favicon = "img/adolforamirezcorona.png"
# Number of posts to show in recent posts list (Optional). Defaults to 10.
#    recentPostsCount = 5
# Content types which are excludes Disqus comments (Optional). Defaults to ["page"]
    disableDisqusTypes = ["page,blog,minipost,service,cursos"]
# If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
    featherIconsCDN = true
    mode = "auto"

[[menu.main]]
      name = "inicio"
      url = "/"
      weight = 1
[[menu.main]]
      name = "blog"
      url = "/blog/"
      weight = 5
[[menu.main]]
      name = "proyectos"
      url = "/proyectos/"
      weight = 6
[[menu.main]]
      name = "info"
      url = "/acerca-de/"
      weight = 10
[[menu.main]]
      name = "english"
      url = "https://medium.com/@adolforismos"
      weight = 15
[[menu.main]]
      name = "micromeditaciones"
      url = "https://micromeditaciones.substack.com"
      weight = 2
[[menu.main]]
      name = "podcast"
      url = "https://anchor.fm/meditacionpsicoterapeutica"
      weight = 3
[[menu.main]]
      name = "libros"
      url = "/libros/"
      weight = 7
      
[[params.social]]
	name = "twitter"
	url = "https://twitter.com/adolforismos"
    icon = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/adolforamirez"
    icon = "instagram"
[[params.social]]
	title = "email"
	url = "mailto:adolforamirez@gmail.com"
    icon = "mail"
[[params.social]]
	title = "rss"
	url = "https://adolforismos.com/index.xml"
    icon = "rss" 

