baseURL = "https://adolforismos.com/"
languageCode = "es-mx"
title = "Adolfo Ramírez Corona"
theme = "ezhil"
enableEmoji = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
pluralizelisttitles = false
paginate = 600
googleAnalytics = "UA-6029436-1"
copyright = "© Adolfo Ramírez Corona"

DefaultContentLanguage  =  "es"  
# copyright  =  "Everything is mine"  

# Enable syntax highlighting.
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[blackfriday]
hrefTargetBlank = true




[permalinks]
#blog = "blog/:slug/"

[taxonomies]
category = "categories"
tag = "tags"

[params]
      description = "Psicoterapeuta, escritor, budista, educador, especialista en audiencias y medios."
      subtitle = "Psicoterapeuta, escritor, budista, educador, especialista en audiencias y medios.."
      mainSections = ["blog"]
     [[menu.main]]
      name = "inicio"
      url = "/"
      weight = 1
     [[menu.main]]
      name = "blog"
      url = "/blog/"
      weight = 5
     [[menu.main]]
      name = "proyectos"
      url = "/proyectos/"
      weight = 6
     [[menu.main]]
      name = "info"
      url = "/acerca-de/"
      weight = 10
dateform = "2006.01.02"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
# description = "Psicoterapeuta, escritor, budista, educador, especialista en audiencias y medios."
faviconfile = "img/adolforamirezcorona.png"
highlightjs = true
name = "Adolfo Ramírez Corona"
author = "adolforismos"
address = "Ciudad de México, México"
year = "2019"
background = "img/adolforamirezcorona.png"
favicon = "img/adolforamirezcorona.png"
# subtitle = "Psicoterapeuta, escritor, budista, educador, especialista en audiencias y medios.."
# Number of posts to show in recent posts list (Optional). Defaults to 10.
recentPostsCount = 5
# Content types which are excluded from recent posts and archive page (Optional). Defaults to ["page"]
excludedTypes = ["page"]
# Content types which are excludes Disqus comments (Optional). Defaults to ["page"]
disableDisqusTypes = ["page,blog"]
# If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
featherIconsCDN = true

showSubheader = true
showServices = true
showRecentWorks = true
showDownload = false
showClients = false

footerEnableContact = false
footerEnableFollowme = true
footerEnableTextWidget = true
footerEnableFormWidget = true


[[params.social]]
	name = "twitter"
	url = "https://twitter.com/adolforismos"
    icon = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/adolforamirez"
    icon = "instagram"
[[params.social]]
	title = "email"
	url = "mailto:adolforamirez@gmail.com"
    icon = "mail"
[[params.social]]
	title = "rss"
	url = "https://adolforismos.com/index.xml"
    icon = "rss" 

