---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/service
  label: Service
  create: all
  match: "**/*"
- type: directory
  path: content/cursos
  label: Cursos
  create: all
  match: "**/*"
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
upload_dir: static/img
public_path: "/img"
front_matter_path: "/uploads"
use_front_matter_path: true
file_template: ":filename:"
version: '0.26'
