---
upload_path: "/static/img"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: "/img/"
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
  blog:
    default_front_matter_template: default
version: '0.26'
