---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
  blog:
    default_front_matter_template: default
upload_dir: static/img
public_path: "/img"
front_matter_path: "/uploads"
use_front_matter_path: true
file_template: ":filename:"
version: '0.26'
