---
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: 'true'
- name: url
  label: Url
  type: text
  hidden: false
  default: ''
- type: select
  name: type
  config:
    source:
      type: simple
    options:
    - blog
    - minipost
  label: type
