---
pages:
- gracias.md
- blog/conocer-y-reconocer.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: 'true'
- name: url
  label: Url
  type: text
  hidden: false
  default: ''
- type: select
  name: type
  config:
    source:
      type: simple
    options:
    - blog
    - minipost
  label: type
- type: datetime
  name: date
  label: date
  config:
    date_format: YYYY-MM-DD
  default: Invalid date
- type: text
  name: author
  label: author
